In [2]:
'''Pandas
1) Pandas DataFrame
2) Pandas Series
3) Pandas Basic Operation'''

'Pandas\nPandas DataFrame\nPandas Series\nPandas Basic Operation'

In [1]:
import pandas as pd #pandas is a class n df is one funtn in it
import numpy as np

In [2]:
np.arange(0,20).reshape(5,4) #numpy array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
##CREATE A DATAFRAME
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"], columns=["Column1","Column2","Column3","Column4"])

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [13]:
df.head() #top 5 records

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [14]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [15]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [16]:
df.tail(2)

Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row5       16       17       18       19

In [17]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [18]:
df[["Column1"]]

Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [20]:
type(df[["Column1"]])

pandas.core.frame.DataFrame

In [19]:
df[["Column1","Column2","Column3"]]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [21]:
df["Column1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [22]:
type(df["Column1"])

pandas.core.series.Series

In [23]:
#series means 1 column without column name, if we combine 2 column it becomes a dataframe

In [24]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
df.loc[["Row1","Row2"]]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [26]:
df.iloc[0:3] #iloc=index location

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11

In [27]:
df.iloc[0:3,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [28]:
df.iloc[2:4,1:3]

Column2  Column3
Row3        9       10
Row4       13       14

In [6]:
np.nan

nan

In [16]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=["Row1","Row2","Row3"],columns=["Column1","Column2","Column3"])

In [17]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [18]:
df.isnull()  #wew get missing values as True

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [19]:
df.isnull().sum()  #shows missing value accr to column

Column1    0
Column2    1
Column3    0
dtype: int64

In [20]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [22]:
df.head()

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [27]:
df["Column1"].value_counts()  #value count in series

Column1
1    2
5    1
Name: count, dtype: int64

In [28]:
df["Column1"].unique()

array([1, 5], dtype=int64)

In [29]:
df["Column1"].nunique()

2

In [31]:
df=pd.DataFrame({'A':[1,2,3],'B':[1,1,1]})

In [32]:
df

A  B
0  1  1
1  2  1
2  3  1

In [33]:
df["A"].unique()

array([1, 2, 3], dtype=int64)

In [34]:
df["B"].unique()

array([1], dtype=int64)

In [36]:
df["B"].nunique()

1

In [37]:
df["A"].nunique()

3

In [38]:
df.nunique()

A    3
B    1
dtype: int64

In [39]:
df

A  B
0  1  1
1  2  1
2  3  1

In [40]:
df.nunique(axis=0) #column wise unique values

A    3
B    1
dtype: int64

In [41]:
df.nunique(axis=1) #row wise unique values

0    1
1    2
2    2
dtype: int64

In [43]:
##CREATE A DATAFRAME
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"], columns=["Column1","Column2","Column3","Column4"])

In [59]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [46]:
df["Column2"]>5

Row1    False
Row2    False
Row3     True
Row4     True
Row5     True
Name: Column2, dtype: bool

In [47]:
df[df["Column2"]>5] #we get rows > 5

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [54]:
df.to_csv('test.csv',index=False)
 #convert into csv file and store in test.csv
#index=false means it will take row 1 row 2 as indexes, it will store test.csv without row index

In [55]:
df1=pd.read_csv('test.csv')

In [56]:
df1

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [65]:
df.to_excel('test.xlsx',index=False)

In [66]:
pd.read_excel('test.xlsx')

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [68]:
pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [73]:
data='{"employee_name":"Krish","email":"krish@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [74]:
data

'{"employee_name":"Krish","email":"krish@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [75]:
type(data)

str

In [77]:
df2=pd.read_json(data)

C:\Users\91983\AppData\Local\Temp\ipykernel_16944\1885955783.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2=pd.read_json(data)


In [78]:
df2

employee_name            email                                  job_profile
0         Krish  krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}

In [79]:
df2['Salary']=100

In [80]:
df2

employee_name            email                                  job_profile  \
0         Krish  krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}   

   Salary  
0     100

In [83]:
dict(df2['job_profile'])[0]['title']

'Team Lead'

In [85]:
pd.read_json(data,orient='records')

C:\Users\91983\AppData\Local\Temp\ipykernel_16944\2317705276.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='records')


employee_name            email                                  job_profile
0         Krish  krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}

In [86]:
pd.read_json(data,orient='index') #column name will became row index

C:\Users\91983\AppData\Local\Temp\ipykernel_16944\131370662.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='index')


0
employee_name                                          Krish
email                                        krish@gmail.com
job_profile    [{'title': 'Team Lead', 'role': 'Developer'}]

In [87]:
pd.read_json(data,orient='columns')

C:\Users\91983\AppData\Local\Temp\ipykernel_16944\3187651850.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='columns')


employee_name            email                                  job_profile
0         Krish  krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}

In [88]:
#these are 3 orientations

In [89]:
import pandas as pd
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

In [90]:
df

col 1 col 2
row 1     a     b
row 2     c     d

In [91]:
df.to_json()

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [92]:
df.to_json(orient="columns")

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [93]:
df.to_json(orient="records")

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [96]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [97]:
df.to_json(orient='index')

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3